package schooljmcp2;



import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * retlibmag.java
 *
 * Created on Dec 2, 2015, 11:44:50 PM
 */



/**
 *
 * @author Lenovo
 */
public class Returnbook extends javax.swing.JFrame {

    /** Creates new form retlibmag */
    public Returnbook() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTF1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1165, 620));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Forte", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Returning dates");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 30, 280, 50);

        jLabel2.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jLabel2.setText("Book id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(670, 110, 270, 30);

        jTF1.setForeground(new java.awt.Color(255, 255, 255));
        jTF1.setBorder(null);
        jTF1.setOpaque(false);
        jTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTF1);
        jTF1.setBounds(680, 150, 327, 16);

        jTextArea1.setBackground(new java.awt.Color(255, 153, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(670, 230, 473, 123);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setForeground(new java.awt.Color(255, 255, 102));
        jButton1.setText("Show Details");
        jButton1.setBorder(null);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(840, 190, 74, 16);

        jButton2.setBackground(new java.awt.Color(102, 204, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 153));
        jButton2.setText("Return");
        jButton2.setBorder(null);
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1070, 380, 38, 16);

        jButton3.setBackground(new java.awt.Color(204, 102, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 153));
        jButton3.setText("Exit");
        jButton3.setBorder(null);
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1080, 410, 21, 16);

        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schooljmcp2/o-BOOK-COFFEE-facebook.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1160, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String id=jTF1.getText();
jTextArea1.setText("");
 try{
          Class.forName("java.sql.Driver");
          Connection con =DriverManager.getConnection("jdbc:mysql://localhost/school","root","hanu");
          Statement stmt =con.createStatement();


String query = "select * from library where bookid='"+id+"';";
ResultSet rs = stmt.executeQuery(query);
while(rs.next()){
    jTextArea1.append("Bookid:-"+rs.getString("bookid")+"\n\nBook name:-"+rs.getString("book_name")+"\n\nIssued to:-"+rs.getString("pname")+"\n\nIssued on:-"+rs.getString("issuedate"));
}


 } catch(Exception e){}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     String id=jTF1.getText();
 try{
          Class.forName("java.sql.Driver");
          Connection con =DriverManager.getConnection("jdbc:mysql://localhost/school","root","hanu");
          Statement stmt =con.createStatement();


String query = "update library set issue=0,pname=null,issuedate=null where bookid="+id+";";
int rs = stmt.executeUpdate(query);
if(rs==1){
    JOptionPane.showMessageDialog(null,"Book return successfully");
}
else{
     JOptionPane.showMessageDialog(null,"Book not returned");
}

 } catch(Exception e){}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
new Navigationframe().setVisible(true);
         this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Returnbook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
